site_name: PyBondi

theme: 
  name: readthedocs

nav:
  - Home: index.md

docs_dir: docs

plugins:
  - search
  - mkdocstrings


markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences


theme:
  name: readthedocs
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate


